# Generated by Django 5.1 on 2024-08-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPPI', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
